name: altair_finance
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=2.2.6
  - pandas>=2.2.3
  - plotly>=6.1.1
  - streamlit>=1.45.1
  - pip
  - pip:
      - yfinance>=0.2.61
